CC = gcc
CFLAGS = -std=c99 -Wall -Wextra -pedantic -O2
LDLIBS =

SOURCES=$(wildcard *.c)
OBJS=$(SOURCES:.c=.o)

all: test

test: $(OBJS)
	$(CC) $(CFLAGS) $(LDLIBS) $^ -o $@

%.o: %.c
	$(CC) $(CLFAGS) $< -c -o $@
