CC=gcc
CFLAGS=-std=c99 -Wall -Wextra -pedantic -O2
LDLIBS=

SRCS=$(wildcard *.c)
OBJS=$(SRCS:.c=.o)

BINARY=test

all: clean $(BINARY)

$(BINARY): $(OBJS)
	$(CC) $(CFLAGS) $(LDLIBS) $^ -o $@

%.o: %.c
	$(CC) $(CFLAGS) $< -c -o $@

clean:
	@rm -f *.o $(BINARY)
